-- =============================================================================
-- Migration: seed public.exercises with the 118 canonical exercises
-- Task: T-105
-- Source: data/exercises.json (118 rows, validated in T-104)
-- Idempotent: yes — on conflict (id) updates all 12 non-id columns, preserving
-- created_at. Safe to re-run whenever canonical metadata changes.
-- =============================================================================

insert into public.exercises (
  id,
  name,
  primary_muscle,
  secondary_muscles,
  equipment,
  movement_pattern,
  is_compound,
  is_unilateral,
  difficulty,
  gender_bias_factor,
  bodyweight_leverage,
  logging_type,
  challenge_suitable
) values
  ('barbell-bench-press', 'Barbell Bench Press', 'chest', ARRAY['triceps','shoulders']::muscle_t[], 'barbell', 'push', true, false, 'intermediate', 1.35, 'none', 'weight_reps', true),
  ('dumbbell-bench-press', 'Dumbbell Bench Press', 'chest', ARRAY['triceps','shoulders']::muscle_t[], 'dumbbell', 'push', true, false, 'intermediate', 1.35, 'none', 'weight_reps', true),
  ('incline-barbell-bench-press', 'Incline Barbell Bench Press', 'chest', ARRAY['shoulders','triceps']::muscle_t[], 'barbell', 'push', true, false, 'intermediate', 1.35, 'none', 'weight_reps', true),
  ('incline-dumbbell-bench-press', 'Incline Dumbbell Bench Press', 'chest', ARRAY['shoulders','triceps']::muscle_t[], 'dumbbell', 'push', true, false, 'intermediate', 1.35, 'none', 'weight_reps', true),
  ('decline-barbell-bench-press', 'Decline Barbell Bench Press', 'chest', ARRAY['triceps']::muscle_t[], 'barbell', 'push', true, false, 'intermediate', 1.35, 'none', 'weight_reps', true),
  ('machine-chest-press', 'Machine Chest Press', 'chest', ARRAY['triceps','shoulders']::muscle_t[], 'machine', 'push', true, false, 'beginner', 1.35, 'none', 'weight_reps', true),
  ('smith-bench', 'Smith Machine Bench Press', 'chest', ARRAY['triceps','shoulders']::muscle_t[], 'smith_machine', 'push', true, false, 'beginner', 1.35, 'none', 'weight_reps', true),
  ('dumbbell-fly', 'Dumbbell Fly', 'chest', ARRAY[]::muscle_t[], 'dumbbell', 'isolation', false, false, 'intermediate', 1.35, 'none', 'weight_reps', true),
  ('cable-fly-high-to-low', 'Cable Fly (High to Low)', 'chest', ARRAY[]::muscle_t[], 'cable', 'isolation', false, false, 'beginner', 1.35, 'none', 'weight_reps', false),
  ('cable-fly-low-to-high', 'Cable Fly (Low to High)', 'chest', ARRAY[]::muscle_t[], 'cable', 'isolation', false, false, 'beginner', 1.35, 'none', 'weight_reps', false),
  ('pec-deck', 'Pec Deck', 'chest', ARRAY[]::muscle_t[], 'machine', 'isolation', false, false, 'beginner', 1.35, 'none', 'weight_reps', true),
  ('push-up', 'Push-Up', 'chest', ARRAY['triceps','shoulders','core']::muscle_t[], 'bodyweight', 'push', true, false, 'beginner', 1.35, 'partial', 'reps_only', true),
  ('chest-dip', 'Chest Dip', 'chest', ARRAY['triceps','shoulders']::muscle_t[], 'bodyweight', 'push', true, false, 'intermediate', 1.35, 'partial', 'reps_only', true),
  ('deadlift', 'Deadlift', 'back', ARRAY['hamstrings','glutes','forearms']::muscle_t[], 'barbell', 'hinge', true, false, 'advanced', 1.20, 'none', 'weight_reps', true),
  ('sumo-deadlift', 'Sumo Deadlift', 'back', ARRAY['glutes','hamstrings']::muscle_t[], 'barbell', 'hinge', true, false, 'advanced', 1.20, 'none', 'weight_reps', true),
  ('barbell-row', 'Barbell Row', 'back', ARRAY['biceps','shoulders']::muscle_t[], 'barbell', 'pull', true, false, 'intermediate', 1.25, 'none', 'weight_reps', true),
  ('pendlay-row', 'Pendlay Row', 'back', ARRAY['biceps','shoulders']::muscle_t[], 'barbell', 'pull', true, false, 'advanced', 1.25, 'none', 'weight_reps', false),
  ('dumbbell-row', 'Dumbbell Row', 'back', ARRAY['biceps']::muscle_t[], 'dumbbell', 'pull', true, true, 'beginner', 1.25, 'none', 'weight_reps', true),
  ('t-bar-row', 'T-Bar Row', 'back', ARRAY['biceps']::muscle_t[], 'barbell', 'pull', true, false, 'intermediate', 1.25, 'none', 'weight_reps', true),
  ('seated-cable-row', 'Seated Cable Row', 'back', ARRAY['biceps']::muscle_t[], 'cable', 'pull', true, false, 'beginner', 1.25, 'none', 'weight_reps', true),
  ('lat-pulldown-wide', 'Lat Pulldown (Wide Grip)', 'back', ARRAY['biceps']::muscle_t[], 'cable', 'pull', true, false, 'beginner', 1.25, 'none', 'weight_reps', true),
  ('lat-pulldown-close', 'Lat Pulldown (Close Grip)', 'back', ARRAY['biceps']::muscle_t[], 'cable', 'pull', true, false, 'beginner', 1.25, 'none', 'weight_reps', true),
  ('pull-up', 'Pull-Up', 'back', ARRAY['biceps','core']::muscle_t[], 'bodyweight', 'pull', true, false, 'advanced', 1.25, 'full', 'reps_only', true),
  ('chin-up', 'Chin-Up', 'back', ARRAY['biceps','core']::muscle_t[], 'bodyweight', 'pull', true, false, 'intermediate', 1.25, 'full', 'reps_only', true),
  ('back-extension', 'Back Extension', 'back', ARRAY['glutes','hamstrings']::muscle_t[], 'bodyweight', 'hinge', false, false, 'beginner', 1.20, 'partial', 'reps_only', true),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', 'back', ARRAY[]::muscle_t[], 'cable', 'isolation', false, false, 'beginner', 1.25, 'none', 'weight_reps', false),
  ('overhead-press', 'Overhead Press', 'shoulders', ARRAY['triceps','core']::muscle_t[], 'barbell', 'push', true, false, 'intermediate', 1.40, 'none', 'weight_reps', true),
  ('seated-dumbbell-press', 'Seated Dumbbell Press', 'shoulders', ARRAY['triceps']::muscle_t[], 'dumbbell', 'push', true, false, 'beginner', 1.40, 'none', 'weight_reps', true),
  ('arnold-press', 'Arnold Press', 'shoulders', ARRAY['triceps']::muscle_t[], 'dumbbell', 'push', true, false, 'intermediate', 1.40, 'none', 'weight_reps', true),
  ('push-press', 'Push Press', 'shoulders', ARRAY['triceps','quads']::muscle_t[], 'barbell', 'push', true, false, 'advanced', 1.40, 'none', 'weight_reps', false),
  ('smith-ohp', 'Smith Machine Overhead Press', 'shoulders', ARRAY['triceps']::muscle_t[], 'smith_machine', 'push', true, false, 'beginner', 1.40, 'none', 'weight_reps', true),
  ('dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'shoulders', ARRAY[]::muscle_t[], 'dumbbell', 'isolation', false, false, 'beginner', 1.35, 'none', 'weight_reps', true),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'shoulders', ARRAY[]::muscle_t[], 'cable', 'isolation', false, true, 'beginner', 1.35, 'none', 'weight_reps', false),
  ('dumbbell-rear-delt-fly', 'Dumbbell Rear Delt Fly', 'shoulders', ARRAY['back']::muscle_t[], 'dumbbell', 'isolation', false, false, 'beginner', 1.35, 'none', 'weight_reps', true),
  ('cable-rear-delt-fly', 'Cable Rear Delt Fly', 'shoulders', ARRAY['back']::muscle_t[], 'cable', 'isolation', false, false, 'beginner', 1.35, 'none', 'weight_reps', false),
  ('face-pull', 'Face Pull', 'shoulders', ARRAY['back']::muscle_t[], 'cable', 'pull', false, false, 'beginner', 1.35, 'none', 'weight_reps', true),
  ('dumbbell-front-raise', 'Dumbbell Front Raise', 'shoulders', ARRAY[]::muscle_t[], 'dumbbell', 'isolation', false, false, 'beginner', 1.35, 'none', 'weight_reps', true),
  ('barbell-shrug', 'Barbell Shrug', 'shoulders', ARRAY['forearms']::muscle_t[], 'barbell', 'isolation', false, false, 'beginner', 1.35, 'none', 'weight_reps', true),
  ('dumbbell-shrug', 'Dumbbell Shrug', 'shoulders', ARRAY['forearms']::muscle_t[], 'dumbbell', 'isolation', false, false, 'beginner', 1.35, 'none', 'weight_reps', true),
  ('barbell-curl', 'Barbell Curl', 'biceps', ARRAY['forearms']::muscle_t[], 'barbell', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', true),
  ('ez-bar-curl', 'EZ-Bar Curl', 'biceps', ARRAY['forearms']::muscle_t[], 'barbell', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', true),
  ('dumbbell-curl', 'Dumbbell Curl', 'biceps', ARRAY['forearms']::muscle_t[], 'dumbbell', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', true),
  ('hammer-curl', 'Hammer Curl', 'biceps', ARRAY['forearms']::muscle_t[], 'dumbbell', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', true),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'biceps', ARRAY[]::muscle_t[], 'dumbbell', 'isolation', false, false, 'intermediate', 1.30, 'none', 'weight_reps', true),
  ('preacher-curl', 'Preacher Curl', 'biceps', ARRAY[]::muscle_t[], 'barbell', 'isolation', false, false, 'intermediate', 1.30, 'none', 'weight_reps', true),
  ('concentration-curl', 'Concentration Curl', 'biceps', ARRAY[]::muscle_t[], 'dumbbell', 'isolation', false, true, 'beginner', 1.30, 'none', 'weight_reps', true),
  ('cable-curl', 'Cable Curl', 'biceps', ARRAY[]::muscle_t[], 'cable', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', false),
  ('cable-hammer-curl-rope', 'Cable Hammer Curl (Rope)', 'biceps', ARRAY['forearms']::muscle_t[], 'cable', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', false),
  ('reverse-curl', 'Reverse Curl', 'biceps', ARRAY['forearms']::muscle_t[], 'barbell', 'isolation', false, false, 'intermediate', 1.30, 'none', 'weight_reps', true),
  ('close-grip-bench-press', 'Close-Grip Bench Press', 'triceps', ARRAY['chest','shoulders']::muscle_t[], 'barbell', 'push', true, false, 'intermediate', 1.35, 'none', 'weight_reps', true),
  ('skull-crusher', 'Skull Crusher', 'triceps', ARRAY[]::muscle_t[], 'barbell', 'isolation', false, false, 'intermediate', 1.30, 'none', 'weight_reps', true),
  ('overhead-dumbbell-extension', 'Overhead Dumbbell Tricep Extension', 'triceps', ARRAY[]::muscle_t[], 'dumbbell', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', true),
  ('cable-pushdown-straight', 'Cable Pushdown (Straight Bar)', 'triceps', ARRAY[]::muscle_t[], 'cable', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', false),
  ('cable-pushdown-rope', 'Cable Pushdown (Rope)', 'triceps', ARRAY[]::muscle_t[], 'cable', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', false),
  ('cable-overhead-extension-rope', 'Cable Overhead Extension (Rope)', 'triceps', ARRAY[]::muscle_t[], 'cable', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', false),
  ('tricep-dip', 'Tricep Dip', 'triceps', ARRAY['chest','shoulders']::muscle_t[], 'bodyweight', 'push', true, false, 'intermediate', 1.35, 'partial', 'reps_only', true),
  ('bench-dip', 'Bench Dip', 'triceps', ARRAY[]::muscle_t[], 'bodyweight', 'push', false, false, 'beginner', 1.30, 'partial', 'reps_only', true),
  ('diamond-push-up', 'Diamond Push-Up', 'triceps', ARRAY['chest']::muscle_t[], 'bodyweight', 'push', true, false, 'intermediate', 1.35, 'partial', 'reps_only', true),
  ('dumbbell-kickback', 'Dumbbell Kickback', 'triceps', ARRAY[]::muscle_t[], 'dumbbell', 'isolation', false, true, 'beginner', 1.30, 'none', 'weight_reps', true),
  ('barbell-wrist-curl', 'Barbell Wrist Curl', 'forearms', ARRAY[]::muscle_t[], 'barbell', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', false),
  ('barbell-reverse-wrist-curl', 'Barbell Reverse Wrist Curl', 'forearms', ARRAY[]::muscle_t[], 'barbell', 'isolation', false, false, 'beginner', 1.30, 'none', 'weight_reps', false),
  ('farmers-walk', 'Farmer''s Walk', 'forearms', ARRAY['shoulders','core']::muscle_t[], 'dumbbell', 'carry', true, false, 'beginner', 1.20, 'none', 'time_seconds', true),
  ('plate-pinch', 'Plate Pinch', 'forearms', ARRAY[]::muscle_t[], 'bodyweight', 'carry', false, false, 'beginner', 1.20, 'none', 'time_seconds', true),
  ('dead-hang', 'Dead Hang', 'forearms', ARRAY['core']::muscle_t[], 'bodyweight', 'isolation', false, false, 'beginner', 1.25, 'full', 'time_seconds', true),
  ('back-squat', 'Back Squat', 'quads', ARRAY['glutes','hamstrings','core']::muscle_t[], 'barbell', 'squat', true, false, 'intermediate', 1.20, 'none', 'weight_reps', true),
  ('front-squat', 'Front Squat', 'quads', ARRAY['glutes','core']::muscle_t[], 'barbell', 'squat', true, false, 'advanced', 1.20, 'none', 'weight_reps', true),
  ('leg-press', 'Leg Press', 'quads', ARRAY['glutes','hamstrings']::muscle_t[], 'machine', 'squat', true, false, 'beginner', 1.20, 'none', 'weight_reps', true),
  ('hack-squat', 'Hack Squat', 'quads', ARRAY['glutes']::muscle_t[], 'machine', 'squat', true, false, 'intermediate', 1.20, 'none', 'weight_reps', true),
  ('smith-squat', 'Smith Machine Squat', 'quads', ARRAY['glutes','hamstrings']::muscle_t[], 'smith_machine', 'squat', true, false, 'beginner', 1.20, 'none', 'weight_reps', true),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'quads', ARRAY['glutes','hamstrings']::muscle_t[], 'dumbbell', 'lunge', true, true, 'intermediate', 1.15, 'partial', 'weight_reps', true),
  ('goblet-squat', 'Goblet Squat', 'quads', ARRAY['glutes','core']::muscle_t[], 'dumbbell', 'squat', true, false, 'beginner', 1.20, 'none', 'weight_reps', true),
  ('walking-lunge', 'Walking Lunge', 'quads', ARRAY['glutes','hamstrings']::muscle_t[], 'dumbbell', 'lunge', true, true, 'beginner', 1.15, 'partial', 'weight_reps', true),
  ('reverse-lunge', 'Reverse Lunge', 'quads', ARRAY['glutes','hamstrings']::muscle_t[], 'dumbbell', 'lunge', true, true, 'beginner', 1.15, 'partial', 'weight_reps', true),
  ('step-up', 'Step-Up', 'quads', ARRAY['glutes']::muscle_t[], 'dumbbell', 'lunge', true, true, 'beginner', 1.15, 'partial', 'weight_reps', true),
  ('leg-extension', 'Leg Extension', 'quads', ARRAY[]::muscle_t[], 'machine', 'isolation', false, false, 'beginner', 1.10, 'none', 'weight_reps', true),
  ('sissy-squat', 'Sissy Squat', 'quads', ARRAY[]::muscle_t[], 'bodyweight', 'squat', false, false, 'advanced', 1.20, 'partial', 'reps_only', false),
  ('burpee', 'Burpee', 'quads', ARRAY[]::muscle_t[], 'bodyweight', 'push', true, false, 'intermediate', 1.15, 'full', 'reps_only', true),
  ('thruster', 'Thruster', 'quads', ARRAY['shoulders','core']::muscle_t[], 'barbell', 'squat', true, false, 'advanced', 1.15, 'none', 'weight_reps', true),
  ('box-jump', 'Box Jump', 'quads', ARRAY['glutes','calves']::muscle_t[], 'bodyweight', 'squat', true, false, 'intermediate', 1.15, 'full', 'reps_only', true),
  ('sled-push', 'Sled Push', 'quads', ARRAY['glutes','calves','core']::muscle_t[], 'machine', 'push', true, false, 'intermediate', 1.15, 'none', 'time_seconds', true),
  ('romanian-deadlift', 'Romanian Deadlift', 'hamstrings', ARRAY['glutes','back']::muscle_t[], 'barbell', 'hinge', true, false, 'intermediate', 1.20, 'none', 'weight_reps', true),
  ('dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'hamstrings', ARRAY['glutes']::muscle_t[], 'dumbbell', 'hinge', true, false, 'beginner', 1.20, 'none', 'weight_reps', true),
  ('stiff-leg-deadlift', 'Stiff-Leg Deadlift', 'hamstrings', ARRAY['glutes']::muscle_t[], 'barbell', 'hinge', true, false, 'intermediate', 1.20, 'none', 'weight_reps', false),
  ('single-leg-rdl', 'Single-Leg Romanian Deadlift', 'hamstrings', ARRAY['glutes','core']::muscle_t[], 'dumbbell', 'hinge', true, true, 'intermediate', 1.20, 'none', 'weight_reps', true),
  ('good-morning', 'Good Morning', 'hamstrings', ARRAY['glutes','back']::muscle_t[], 'barbell', 'hinge', true, false, 'advanced', 1.20, 'none', 'weight_reps', false),
  ('lying-leg-curl', 'Lying Leg Curl', 'hamstrings', ARRAY[]::muscle_t[], 'machine', 'isolation', false, false, 'beginner', 1.10, 'none', 'weight_reps', true),
  ('seated-leg-curl', 'Seated Leg Curl', 'hamstrings', ARRAY[]::muscle_t[], 'machine', 'isolation', false, false, 'beginner', 1.10, 'none', 'weight_reps', true),
  ('nordic-hamstring-curl', 'Nordic Hamstring Curl', 'hamstrings', ARRAY[]::muscle_t[], 'bodyweight', 'isolation', false, false, 'advanced', 1.20, 'partial', 'reps_only', false),
  ('glute-ham-raise', 'Glute-Ham Raise', 'hamstrings', ARRAY['glutes']::muscle_t[], 'machine', 'hinge', true, false, 'advanced', 1.20, 'partial', 'reps_only', false),
  ('barbell-hip-thrust', 'Barbell Hip Thrust', 'glutes', ARRAY['hamstrings']::muscle_t[], 'barbell', 'hinge', true, false, 'intermediate', 1.15, 'none', 'weight_reps', true),
  ('machine-hip-thrust', 'Machine Hip Thrust', 'glutes', ARRAY['hamstrings']::muscle_t[], 'machine', 'hinge', true, false, 'beginner', 1.15, 'none', 'weight_reps', true),
  ('glute-bridge', 'Glute Bridge', 'glutes', ARRAY['hamstrings']::muscle_t[], 'barbell', 'hinge', true, false, 'beginner', 1.15, 'none', 'weight_reps', true),
  ('cable-kickback', 'Cable Kickback', 'glutes', ARRAY[]::muscle_t[], 'cable', 'isolation', false, true, 'beginner', 1.15, 'none', 'weight_reps', false),
  ('cable-pull-through', 'Cable Pull-Through', 'glutes', ARRAY['hamstrings']::muscle_t[], 'cable', 'hinge', true, false, 'beginner', 1.15, 'none', 'weight_reps', false),
  ('hip-abduction-machine', 'Hip Abduction (Machine)', 'glutes', ARRAY[]::muscle_t[], 'machine', 'isolation', false, false, 'beginner', 1.15, 'none', 'weight_reps', true),
  ('frog-pump', 'Frog Pump', 'glutes', ARRAY[]::muscle_t[], 'bodyweight', 'isolation', false, false, 'beginner', 1.15, 'partial', 'reps_only', true),
  ('single-leg-hip-thrust', 'Single-Leg Hip Thrust', 'glutes', ARRAY['hamstrings']::muscle_t[], 'bodyweight', 'hinge', false, true, 'intermediate', 1.15, 'partial', 'reps_only', true),
  ('curtsy-lunge', 'Curtsy Lunge', 'glutes', ARRAY['quads']::muscle_t[], 'dumbbell', 'lunge', true, true, 'intermediate', 1.15, 'partial', 'weight_reps', true),
  ('kettlebell-swing', 'Kettlebell Swing', 'glutes', ARRAY['hamstrings','core']::muscle_t[], 'kettlebell', 'hinge', true, false, 'intermediate', 1.15, 'none', 'weight_reps', true),
  ('standing-calf-raise', 'Standing Calf Raise', 'calves', ARRAY[]::muscle_t[], 'machine', 'isolation', false, false, 'beginner', 1.10, 'none', 'weight_reps', true),
  ('seated-calf-raise', 'Seated Calf Raise', 'calves', ARRAY[]::muscle_t[], 'machine', 'isolation', false, false, 'beginner', 1.10, 'none', 'weight_reps', true),
  ('donkey-calf-raise', 'Donkey Calf Raise', 'calves', ARRAY[]::muscle_t[], 'machine', 'isolation', false, false, 'beginner', 1.10, 'none', 'weight_reps', true),
  ('leg-press-calf-raise', 'Leg Press Calf Raise', 'calves', ARRAY[]::muscle_t[], 'machine', 'isolation', false, false, 'beginner', 1.10, 'none', 'weight_reps', true),
  ('smith-machine-calf-raise', 'Smith Machine Calf Raise', 'calves', ARRAY[]::muscle_t[], 'smith_machine', 'isolation', false, false, 'beginner', 1.10, 'none', 'weight_reps', true),
  ('single-leg-dumbbell-calf-raise', 'Single-Leg Dumbbell Calf Raise', 'calves', ARRAY[]::muscle_t[], 'dumbbell', 'isolation', false, true, 'beginner', 1.10, 'none', 'weight_reps', true),
  ('plank', 'Plank', 'core', ARRAY['shoulders']::muscle_t[], 'bodyweight', 'core', false, false, 'beginner', 1.00, 'partial', 'time_seconds', true),
  ('side-plank', 'Side Plank', 'core', ARRAY[]::muscle_t[], 'bodyweight', 'core', false, true, 'beginner', 1.00, 'partial', 'time_seconds', true),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'core', ARRAY[]::muscle_t[], 'bodyweight', 'core', false, false, 'intermediate', 1.00, 'full', 'reps_only', true),
  ('hanging-knee-raise', 'Hanging Knee Raise', 'core', ARRAY[]::muscle_t[], 'bodyweight', 'core', false, false, 'beginner', 1.00, 'full', 'reps_only', true),
  ('cable-crunch', 'Cable Crunch', 'core', ARRAY[]::muscle_t[], 'cable', 'core', false, false, 'beginner', 1.00, 'none', 'weight_reps', true),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', 'core', ARRAY['shoulders']::muscle_t[], 'bodyweight', 'core', false, false, 'advanced', 1.00, 'partial', 'reps_only', true),
  ('decline-sit-up', 'Decline Sit-Up', 'core', ARRAY[]::muscle_t[], 'bodyweight', 'core', false, false, 'beginner', 1.00, 'partial', 'reps_only', true),
  ('russian-twist', 'Russian Twist', 'core', ARRAY[]::muscle_t[], 'dumbbell', 'core', false, false, 'beginner', 1.00, 'partial', 'reps_only', true),
  ('cable-wood-chopper', 'Cable Wood Chopper', 'core', ARRAY[]::muscle_t[], 'cable', 'core', false, true, 'beginner', 1.00, 'none', 'weight_reps', true),
  ('pallof-press', 'Pallof Press', 'core', ARRAY[]::muscle_t[], 'cable', 'core', false, false, 'beginner', 1.00, 'none', 'weight_reps', true),
  ('dead-bug', 'Dead Bug', 'core', ARRAY[]::muscle_t[], 'bodyweight', 'core', false, false, 'beginner', 1.00, 'partial', 'reps_only', true),
  ('v-up', 'V-Up', 'core', ARRAY[]::muscle_t[], 'bodyweight', 'core', false, false, 'intermediate', 1.00, 'partial', 'reps_only', true),
  ('weighted-sit-up', 'Weighted Sit-Up', 'core', ARRAY[]::muscle_t[], 'bodyweight', 'core', false, false, 'intermediate', 1.00, 'partial', 'weight_reps', true)
on conflict (id) do update set
  name                = excluded.name,
  primary_muscle      = excluded.primary_muscle,
  secondary_muscles   = excluded.secondary_muscles,
  equipment           = excluded.equipment,
  movement_pattern    = excluded.movement_pattern,
  is_compound         = excluded.is_compound,
  is_unilateral       = excluded.is_unilateral,
  difficulty          = excluded.difficulty,
  gender_bias_factor  = excluded.gender_bias_factor,
  bodyweight_leverage = excluded.bodyweight_leverage,
  logging_type        = excluded.logging_type,
  challenge_suitable  = excluded.challenge_suitable;
